try using workflow dispatch to trigger rebuilds

diff --git a/.github/workflows/bclconvert-build.yml b/.github/workflows/bclconvert-build.yml
--- a/.github/workflows/bclconvert-build.yml
+++ b/.github/workflows/bclconvert-build.yml
@@ -1,19 +1,22 @@
 name: bclconvert-build
 
-on:
-  push:
-    branches: [ main ]
+on: 
+  workflow_dispatch:
+    inputs:
+      version:
+        description: Version of the tool to download
+        required: true
+      latest:
+        description: Whether to mark the image as latest
+        type: boolean
+        required: true
 
 jobs:
   bclconvert-build:
+    env:
+      base_name: ghcr.io/data-intuitive/bclconvert
     runs-on: ubuntu-latest
     if: "!contains(github.event.head_commit.message, 'ci skip')"
-
-    strategy:
-      fail-fast: false
-      matrix:
-        config:
-        - {version: "3.10", tag: "ghcr.io/data-intuitive/bclconvert:3.10,ghcr.io/data-intuitive/bclconvert:latest"}
 
     steps:
     - uses: actions/checkout@v2
@@ -32,6 +35,8 @@ jobs:
 
     - name: Download BCL Convert
       run: |
+        echo "Error: allow passing version number to component"
+        exit 1
         bin/viash run src/bclconvert/download_bclconvert/config.vsh.yaml -- \
           --email "${{ secrets.ILLUMINA_EMAIL }}" \
           --password "${{ secrets.ILLUMINA_PASSWORD }}" \
@@ -47,9 +52,13 @@ jobs:
         
     - name: Build image
       run: |
+        version="${{ github.event.inputs.version }}"
+        tag=$base_name:$version
+        if [[ "${{ github.event.inputs.version }}" == "latest" ]]; then
+          tag="$tag,$base_name:latest"
         bin/viash run src/bclconvert/build_bclconvert/config.vsh.yaml -- \
           --input "bclconvert.rpm" \
-          --tag "${{ matrix.config.tag }}" \
+          --tag "$tag" \
           --push
 
     - name: Image digest
